### ISSUE TITLE
Documentation for creating an element with multiple inputs

### ISSUE THREAD

**Issue by jacobstern** [membraneframework/membrane-core#142]
I'm investigating this library for an application that involves combining multiple audio streams to a single output. I was looking into creating an element that has multiple input pads but it's not clear what the workflow should be as the [demand](https://hexdocs.pm/membrane_core/Membrane.Element.Action.html#t:demand_t/0) command only allows pulling from one input pad at a time. What is the recommended solution here?

**Comment by mat-hek** [comment]
Hi @jacobstern, you just need to return demand for each pad you wish to receive the data from, like this:
```elixir
def handle_... do
  demands = [:pad1, :pad2, ...] |> Enum.map(fn pad -> {:demand, {pad, size}} end)
  {{:ok, demands}, state}
end
```

**Comment by jacobstern** [comment]
Thanks for the quick response! What is the recommended pattern for implementing `handle_process` for multiple input pads to produce audio for one output pad? I've tried a couple schemes and I've been running into `:start_of_stream_already_received` errors.

**Comment by jacobstern** [comment]
Never mind, I think I just need to return `{:ok, state}` from one of the callbacks. Will try this and follow up with a more detailed query if there seems to be a problem. Thanks!
