### ISSUE TITLE
Fail if pads with incompatible modes are linked

### ISSUE THREAD

**Issue by mat-hek** [membraneframework/membrane-core#39]
- [ ] Fail when pull source is linked to push sink
- [ ] Warn when push source is linked to pull sink, and enable pull buffer toilet mode automatically

**Comment by mspanc** [comment]
@mat-hek is it still opened since you merged this?

**Comment by mat-hek** [comment]
I only suggested it can be solved in that PR, but finally it wasn't (only direction is validated)

**Comment by mspanc** [comment]
According to the planning meeting on 25.06.2018 it may be postponed.
