### ISSUE TITLE
Add some element error handling mechanism in pipeline

### ISSUE THREAD

**Issue by mat-hek** [membraneframework/membrane-core#41]
Currently errors returned from callbacks always cause failure of pipeline, and cannot be handled in any way. We should provide a mechanism that could make it possible recover such errors at pipeline level. The potential problem with this solution is that it will probably require calls from element to pipeline, while such calls in opposite direction happen to be made, what may lead to deadlocks.

**Comment by mspanc** [comment]
According to the planning meeting on 25.06.2018 it can be resolved later on.
