### ISSUE TITLE
Refactor callbacks signatures

### ISSUE THREAD

**Issue by mat-hek** [membraneframework/membrane-core#47]
- [x] handle_prepare:
```elixir
handle_prepare(:stopped, state)
```
to 
```elixir
handle_prepare_to_play(state)
```
similarly `handle_prepate_to_stop`

- [x] `handle_{write,process}` -> `handle_*_list`, e.g. `handle_write` -> `handle_write_list`
- [x] `handle_{write,process}1` -> `handle_*`, e.g. `handle_write1` -> `handle_write`
- [x]  `def_known_sink_pads` -> `def_sink_pads`, `def_known_source_pads` -> `def_source_pads`

**Comment by bblaszkow06** [comment]
Also, because there is `:redemand` action, `handle_demand1` can be removed
