### ISSUE TITLE
Change approach to code reuse

### ISSUE THREAD

**Issue by mat-hek** [membraneframework/membrane-core#48]
Current way of sharing code between modules in the core is putting that code inside the `__using__` macro. As this approach has some disadvantages, and we should aim to limit amount of generated code, we need to refactor that modules. One of ways is to pass the name of module containing implementation to each function of the abstraction. Some macros may also be used to improve this approach.

Modules to be refactored:

- [x] Membrane.Element.Manager.Common
- [x] Membrane.Mixins.CallbackHandler
- [x] Membrane.Mixins.Playback

**Comment by mspanc** [comment]
Partially overlaps #65
