### ISSUE TITLE
Consider unifying default behaviour of `demand` action and `handle_demand` callback between different element types

### ISSUE THREAD

**Issue by mat-hek** [membraneframework/membrane-core#66]
Currently:
- in filter, `handle_demand` receives always entire demand, and returning `demand` overrides previous demand
- in source, `handle_demand` receives only the new demand, except for being caused by `redemand` action, in which case it receives entire demand
- in sink, returning `demand` means adding it to existing demand

Imho we should change this, so that:
- entire demand is always passed to `handle_demand`
- returning `demand` always causes overriding existing demand

As in some cases different behaviour is required, we could:
- support passing lambda as a size to demand, such as `demand: {:sink, & &1+1}`
- pass the new demand to `handle_demand` in context

**Comment by mspanc** [comment]
Not a top priority but would be good to have in the upcoming release as it is breaking change.

**Comment by bblaszkow06** [comment]
Also, because there is `:redemand` action, `handle_demand1` can be removed
