### ISSUE TITLE
Support for different payload types

### ISSUE THREAD

**Issue by mat-hek** [membraneframework/membrane-core#68]
Currently we use only one payload type - erlang binary. We should support also a native C payload type, mutable and passed by pointer. This is necessary for processing large amount of data (such as high quality video).
We should consider:
- Way of passing pointer to different NIFs
- Monitoring lifecycle of payload
- Adding payload type to caps
- Size of each payload type should be accessible from elixir with possibly low overhead, because its used frequently to handle demand-related stuff.
- Payload should be automatically converted by core if type is not supported by element.

**Comment by mspanc** [comment]
This is a strict requirement for adding video so according to the planning meeting on 25.06.2018  it should be done ASAP.

**Comment by mspanc** [comment]
Caps should contain information about the payload type that may arrive to the element.
