### ISSUE TITLE
Add video support

### ISSUE THREAD

**Issue by mat-hek** [membraneframework/membrane-core#70]
This involves:
- [ ] checking how the system behaves when sending and processing much bigger data chunks
- [x] adding abstraction over NIFs (https://github.com/membraneframework/membrane-native/issues/1)
- [x] adding native payload type #68

**Comment by mspanc** [comment]
@mat-hek @jarekdragan the last checkbox (adding mechanism for streams synchronization) is huge, it should not be marked as v0.2.

**Comment by mrkaspa** [comment]
What is the status on this I would like to test this feature

**Comment by mat-hek** [comment]
@mrkaspa In fact, this is already done. Some elements that may be useful:
- https://github.com/membraneframework/membrane-element-ffmpeg-h264
- https://github.com/membraneframework/membrane-element-sdl
- https://github.com/membraneframework/membrane-element-rtp-h264
